version: '3.8'
services:
  app-redis-server:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  app-db:
    image: postgres:latest
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
    env_file:
      - src/env_config/.env
    ports:
      - "5432:5432"
  app-web-server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app-db
      - app-redis-server
    restart: on-failure
    volumes:
      - .:/server
    ports:
      - "8000:8000"
  app-celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app-web-server
      - app-redis-server
    restart: always
    volumes:
      - .:/server
    env_file:
      - src/env_config/.env
    command:
      - bash
      - -c
      - celery -A main.celery worker -B -l info
volumes:
  app-db-data: