version: '3.8'
services:
  appDB:
    image: postgres:latest
    restart: always
    volumes:
      - app-db-data:/var/lib/postgresql/data
    env_file:
      - src/.env
    ports:
      - "5432:5432"
  app-web-server:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - appDB
    restart: on-failure
    volumes:
      - .:/server
    ports:
      - "8000:8000"
volumes:
  app-db-data: